require("express-async-errors");
const express = require("express");
const cors = require("cors");
const optionalAuth = require("./middleware/optionalAuth");
const presalesRoutes = require("./routes/presalesRoutes");
const proposalRoutes = require("./routes/proposalRoutes");
const callScriptRoutes = require("./routes/callScriptRoutes");
const objectionsRoutes = require("./routes/objectionsRoutes");
const competitorsRoutes = require("./routes/competitorsRoutes");
const followUpRoutes = require("./routes/followUpRoutes");
const briefingRoutes = require("./routes/briefingRoutes");
const publicBriefingRoutes = require("./routes/publicBriefingRoutes");
const dealEngineRoutes = require("./routes/dealEngineRoutes");
const callEngineRoutes = require("./routes/callEngineRoutes");
const authRoutes = require("./routes/authRoutes");
const reportsRoutes = require("./routes/reportsRoutes");
const analyticsRoutes = require("./routes/analyticsRoutes");
const errorHandler = require("./middleware/errorHandler");

const app = express();

app.use(cors());
app.use(express.json());
app.use(optionalAuth);
app.use("/api/auth", authRoutes);
app.use("/api/reports", reportsRoutes);
app.use("/api/analytics", analyticsRoutes);
app.use("/api/presales", presalesRoutes);
app.use("/api/proposal", proposalRoutes);
app.use("/api/call-script", callScriptRoutes);
app.use("/api/objections", objectionsRoutes);
app.use("/api/competitors", competitorsRoutes);
app.use("/api/follow-up", followUpRoutes);
app.use("/api/briefings", briefingRoutes);
app.use("/api/public/briefings", publicBriefingRoutes);
app.use("/api/deal", dealEngineRoutes);
app.use("/api/call", callEngineRoutes);
app.use(errorHandler);

module.exports = app;
